### ISSUE TITLE
Feature request: Monthly range with configurable day date

### ISSUE THREAD

**Issue by Chouffy** [Sanmeet007/logger#13]
Hi again!

This is a continuation of #12 . As a reminder "I wanted to use it to track my call duration on a given period: I do have 2 hours of call included in my cell plan, so I wanted to check on device how much I used for the period."
For some cell operators, the period doesn't start on the 1st of the month, but on another day (7 in my case).
If I want to track my consumption within my period, I would need to define a custom time range, which is feasible today using the Filter panel.

It would enhance the experience to define a "period start day", so one can quickly select a Date range "Monthly cycle" for instance, and track the duration of all call done during the provider-defined period (pending of #12  to be completed of course).

This behavior would be very similar to how "Data warning and limit" works within Android for mobile data.

Again, thanks a lot for all you do!

**Comment by Sanmeet007** [comment]
@Chouffy  Hi again ! 

Thank you once again for your detailed feedback and for sharing your thoughts on improving the app experience!

I completely agree that the ability to define a "period start day" and track calls within your provider-defined cycle would enhance the experience, especially for users with varying billing cycles. However, the custom date range feature you’re suggesting would indeed be quite challenging to implement with the current modules I’m using, particularly because building a custom date-time picker involves significant complexity.

For now, I’m afraid I won’t be able to introduce this feature, but you can still manually select a custom date range using the current date selector dialog. I understand this isn't exactly what you're looking for, but it's the best option at the moment.

I’m really sorry for the inconvenience, but I’ll definitely consider this enhancement for a future release! Thank you again for your continued support and understanding.

![Screenshot_20240927_182536](https://github.com/user-attachments/assets/08cd236e-5d91-4d1d-a9ff-27b1d9e6fb16)
^ Current remedy 

Sorry you would have to wait a bit longer :(

**Comment by Chouffy** [comment]
Hi @Sanmeet007,

I totally understand your point, this was more a Quality of Life request more than anything - this shouldn't be done if it's too complex to do 😊 

Thanks that you look at it!
