### ISSUE TITLE
Update call log with names from `Contacts`

### ISSUE THREAD

**Issue by sphh** [Sanmeet007/logger#20]
`Logger` depends on the cached name saved in the call log. As it turned out, some dialers do not save that name in the log and hence the name is always shown as `Unknown` (#16 and https://github.com/bitfireAT/davx5-ose/discussions/1196).

It is very reasonable to not do the name lookup because of performance reasons, but until all the dialers store the names in the call log, it would still be great to see the real names. I can imagine two approaches:
- A setting (off by default), which enables the time consuming lookup (not looking up every entry separately, but caching the number-names pair to improve speed); *or*
- A button for a one-off update of the call log: This would write the looked-up names back into the call log (this is also helpful, if new entries were added to the `Contacts` or contact names were changed).

Would that be possible? What do you think?

**Comment by Sanmeet007** [comment]
One step ahead, @sphh ! I was actually writing the updated application this morning because, for me, issues are also a type of contribution, and yours was invaluable. I’ve added the feature you were looking for – it's available in the Advanced Settings with a "Sync Now" button that will sync the contact names with the call logs!

You can update your app to the latest version [2.7.0](https://github.com/Sanmeet007/logger/releases/tag/v2.7.0) to see the feature in action.

![Group 20](https://github.com/user-attachments/assets/f8fde00b-6012-4fab-8cc0-3af8cc82d539)

**Comment by sphh** [comment]
:+1:
