### ISSUE TITLE
not importing CSV

### ISSUE THREAD

**Issue by hlvs44** [Sanmeet007/logger#5]
Hallo,
I'm trying to import my CSV file after Phone resetting. 
Both functions in the upper bar ask me where to save the file and not where is located the file "CSV" to import.
I think it's a bug.
I hope It's possible to solve as I'd like to have the call history on my phone.
Thanks a lot.
ale

**Comment by Sanmeet007** [comment]
Thank you for reaching out and sharing your experience with the Logger app.

I understand that you want to import call logs from the generated CSV file after resetting your phone. However, I want to clarify that the Logger app is designed primarily to export call logs in CSV format for backup and safekeeping. This feature ensures that you can preserve your call log history, especially since phones tend to delete older call logs as new calls are made.

The main purpose of the Logger app is to help you extract call logs for analysis or any other use you might have for your call data. Unfortunately, **importing call logs back into the app is not a function** that the app currently supports.

I am deeply sorry if there was any misunderstanding or if the app's functionality did not meet your expectations in this regard. Your feedback is invaluable, and I will certainly take it into consideration for future updates and improvements.

Thank you for using Logger, and I hope it continues to be a helpful tool for you. If you have any other questions or need further assistance, please don't hesitate to reach out.

Warm regards,

Sanmeet

**Comment by hlvs44** [comment]
Thank you Sanmeet007,
the app is very nice, useful and self-explainatory, however in the benefits list it is clearly indicated that this app has a feature to import CSV data.
I think you should correct the description or (better as I hope) integrate it in the app.
Have a nice day.
ale

Benefits:

-     Gain valuable insights by analyzing your call log data exported in a readily usable CSV format.
-     Maintain organized call records outside your device for future reference or data analysis.
-     Analyze call statistics, call directions, and durations directly on your device, empowering informed decision-making.
-     Easily **import** and export CSV files within the app, ensuring seamless data organization and accessibility.

**Comment by Sanmeet007** [comment]
I owe you an apology for the confusion caused. It was indeed a blunder on my part. Upon reviewing the readme more carefully, I realize I should have clarified that while the app currently supports exporting call logs as CSV files, it does not yet include the feature to import them.

Originally, I had planned to incorporate an import feature for users to bring back exported files, but regrettably, I haven't figured it out yet. This oversight led to outdated information in the readme.

I deeply regret any inconvenience or misunderstanding this may have caused. I want to assure you that I am committed to adding the import feature, and I will promptly update the readme to reflect the correct details.

Once again, I apologize for the confusion and for not addressing this issue sooner. Your understanding is greatly appreciated.

**Comment by Sanmeet007** [comment]
Hey @hlvs44 , I sincerely apologize for any inconvenience caused last time. I'm pleased to inform you  that the feature you enquired ( rather suggested ) is now live in the latest version ([v2.1.7](https://github.com/Sanmeet007/logger/releases/tag/v2.1.7)) of the Logger app! It's been a journey, but I'm thrilled to see it finally implemented. This update also ensures compatibility with previously exported call logs in CSV format. Your input has truly made a difference—thank you for your valuable suggestion!

Really sorry for last time too!
