### ISSUE TITLE
Rename app to "Call Logger"

### ISSUE THREAD

**Issue by caydey** [Sanmeet007/logger#8]
Current name for the app is not very informative

**Comment by Sanmeet007** [comment]
Hi @caydey,

Thank you for suggesting a new name for the app. I appreciate your input and contributions.

While I understand the current name may not be very informative, I've decided to keep it for now because it is more generic and I have developed and maintained it for 2 years. Changing it at this stage could cause confusion among existing users.

I'm open to suggestions on improving the app's description or tagline to make it more informative. Your feedback is always valuable.

I hope you understand, and thanks for the PR.
